version: '3'
services:
  client:
    image: 'mranmi/multy-client'
    hostname: client
    environment:
      - WDS_SOCKET_PORT=0
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    hostname: nginx
    depends_on:
      - api
      - client
    restart: always
    image: 'mranmi/multy-nginx'
    ports:
      - '80:80'
  server:
    image: mranmi/multy-server
    hostname: api
  worker:
    image: 'mranmi/multy-wrker'
    hostname: worker

