version: '3'
services:
  client:
    image: 'mranmi/multy-client'
    mem_limit: 128m
    hostname: client
    environment:
      - WDS_SOCKET_PORT=0
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    hostname: nginx
    mem_limit: 128m
    depends_on:
      - api
      - client
    restart: always
    image: 'mranmi/multy-nginx'
    ports:
      - '80:80'
  api:
    image: 'mranmi/multy-server'
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'mranmi/multy-worker'
    hostname: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

