name: Deploy Frontend to AWS EBS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "elasticbeanstalk-eu-central-1-214332176162"
  EB_APPLICATION_NAME : "docker-complex"
  EB_ENVIRONMENT_NAME : "Dockercomplex-env"
  DEPLOY_PACKAGE_NAME : "dockerized_AMinenko-docker-react_${{ github.sha }}.zip"
  AWS_REGION_NAME : "eu-central-1"

on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo and build images and push to docker hub
        uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mranmi/multy-client ./client
      - run: docker build -t mranmi/multy-nginx ./nginx
      - run: docker build -t mranmi/multy-server ./server
      - run: docker build -t mranmi/multy-worker ./worker
      - run: docker push mranmi/multy-client
      - run: docker push mranmi/multy-nginx
      - run: docker push mranmi/multy-server
      - run: docker push mranmi/multy-worker
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      # - run: aws s3 cp docker-compose.yml s3://docker-compose.yml
      # - run: echo "Images are built and deployed to Docker hub. Docker-compose.yml is copied to the bucket "

#        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
    
      
      - name: Print Happy message for build step finish
      
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: ${{ env.EB_APPLICATION_NAME }}
      #     environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
      #     existing_bucket_name: ${{ env.EB_PACKAGE_S3_BUCKET_NAME }}
      #     region: ${{ env.AWS_REGION_NAME }}
      #     version_label: ${{ github.sha }}
      #     deployment_package: ${{ env.DEPLOY_PACKAGE_NAME }}